sources:
  - name: landing
    description: The primary source system for order management system(OMS) data analytics.  
    database: SNOWFLAKE_LEARNING_DB
    schema: L1_LANDING

    tables:
      - name: customers
        description: The customers table from order management system(OMS).      
        identifier: customers
      - name: orders
        description: The orders table from order management system(OMS).      
        identifier: orders
      - name: orderitems
        description: The orderitems table from order management system(OMS).      
        identifier: orderitems
      - name: employees
        description: The employees table from order management system(OMS).      
        identifier: employees
        # columns:
        #   - name: address
        #     description: Full Address of emplyees for Transport Arrangements.          
        #     tests:
        #       - not_null
        #       - string_not_empty